install:
	sudo ln -s `pwd`/olleh_wifi_off /usr/local/bin/olleh_wifi_off
	sudo ln -s `pwd`/olleh_wifi_on /usr/local/bin/olleh_wifi_on

clean:
	sudo rm /usr/local/bin/olleh_wifi_off
	sudo rm /usr/local/bin/olleh_wifi_on
